export const AUTH_COPY = {
  subtitleRemote: '输入邮箱，我们会发送一个一次性登录链接。',
  magicLinkSent: '登录链接已发送，请查收邮件。链接 15 分钟内有效。',
  sendMagicLink: '发送一次性登录链接',
  passwordLogin: '使用密码登录',
  magicLinkLogin: '使用邮箱链接登录',
  registrationClosed: '当前暂未开放新用户注册。',
  legalRequired: '请先阅读并同意用户协议与隐私政策。',
  registrationDisabled: '当前暂未开放注册。',
  loading: '请稍候…',
  login: '登录',
  register: '注册并进入',
  legalPrefix: '我已阅读并同意',
  legalTerms: '用户协议',
  legalAnd: '与',
  legalPrivacy: '隐私政策',
  displayNameLabel: '昵称（可选）',
  displayNamePlaceholder: '怎么称呼你',
  emailLabel: '邮箱',
  passwordLabel: '密码',
  passwordPlaceholder: '至少 6 位'
} as const
